# Generated by Django 2.0 on 2018-08-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to='article/%Y/%m', verbose_name='封面图'),
        ),
    ]
