# Generated by Django 2.0 on 2018-08-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180811_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='view_nums',
            field=models.IntegerField(default=0, verbose_name='浏览人数'),
        ),
    ]
