# Generated by Django 2.0.7 on 2018-08-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='add_time',
        ),
    ]
