# Generated by Django 2.0.7 on 2018-08-20 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_galleryimage_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(blank=True, upload_to='banner/%Y/%m', verbose_name='图库轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '图库轮播图',
                'verbose_name_plural': '图库轮播图',
            },
        ),
    ]
